server:
  port: 8088

spring:
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password: password
    timeout: 2000 # 连接或读取超时时长（毫秒）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
  datasource:
    username: sde
    password: postgres
    url: jdbc:postgresql://localhost:5432/online-code-generator
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1830000
      maximum-pool-size: 10

mybatis-plus:
  global-config:
    #机器 ID 部分(影响雪花ID)
    workerId: 1
    #数据标识 ID 部分(影响雪花ID)(workerId 和 datacenterId 一起配置才能重新初始化 Sequence)
    datacenterId: 18
    db-config:
      insert-strategy: ignored  # 忽略判断，
      update-strategy: ignored  # 忽略判断，字段取值为null，即把null值保存到数据库，而不是忽略这个null的字段
  refresh-mapper: true
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.ascs.xinfangguanli.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    return-instance-for-empty-row: true
    map-underscore-to-camel-case: true

rate-limiter.one-second.limit: 2000
url:
  authentication:
    white-list: /oauth/login,/oauth/logout,/oauth/user-info,/oauth/captcha

